version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"

  web:
    build: ./userapi/src
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: userdb
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      - db

